name: CI con AutoCommit

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write   # ðŸ‘ˆ IMPORTANTE: permite que el bot pueda hacer commits/push


jobs:
  test-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar pytest
        run: pip install pytest
      - name: Instalar pdoc
        run: pip install pdoc

      - name: Ejecutar script de tests y actualizar README
        run: python update_readme.py

      - name: Commit automÃ¡tico del README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README con estado de tests"
          file_pattern: README.md


      - name: Actualizando documentaciÃ³n web
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "documentaciÃ³n web actualizada"
          file_pattern: docs/**